### ISSUE TITLE
Online Interactive demo does not work 

### ISSUE THREAD

**Issue by grethler** [MadryLab/photoguard#5]
Runtime error
 File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 8b48729a-bb53-4197-8465-5a79af9d8b22)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1371, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 15, in <module>
    pipe_inpaint = StableDiffusionInpaintPipeline.from_pretrained(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 454, in from_pretrained
    config_dict = cls.load_config(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 354, in load_config
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-inpainting does not appear to have a file named model_index.json.

**Comment by aguyinmontreal** [comment]
Online Interactive demo is still down

**Comment by Daanniieelll** [comment]
Same errors, can somebody help me to fix it?
